# Generated by Django 3.2.12 on 2022-02-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listedgames',
            options={'verbose_name_plural': 'Listed Games'},
        ),
        migrations.AddField(
            model_name='listedgames',
            name='theme_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
