# Generated by Django 3.2.12 on 2022-02-05 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220205_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listedgames',
            name='theme_image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GameAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=300)),
                ('rate', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.listedgames')),
            ],
        ),
    ]
