# Generated by Django 3.2.12 on 2022-02-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220205_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedgames',
            name='slug',
            field=models.SlugField(default='pubg'),
            preserve_default=False,
        ),
    ]
