# Generated by Django 3.2.12 on 2022-02-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_listedgames_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaccounts',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
