# Generated by Django 3.2.12 on 2022-02-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cartorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='game_accounts',
            field=models.ManyToManyField(to='core.CartItem'),
        ),
    ]
