# Generated by Django 3.2.12 on 2022-02-13 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220206_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('game_acount', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.gameaccounts')),
            ],
        ),
    ]
