# Generated by Django 3.2.12 on 2022-02-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_postimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='game_acount',
            new_name='game_account',
        ),
        migrations.RemoveField(
            model_name='gameaccounts',
            name='image',
        ),
    ]
