# Generated by Django 3.2.12 on 2022-02-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220217_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='received',
        ),
    ]
