# Generated by Django 3.2.12 on 2022-02-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_cartorder_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameaccounts',
            name='sold',
        ),
    ]
