# Generated by Django 3.2.12 on 2022-02-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_gameaccounts_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.ImageField(upload_to='static/media'),
        ),
    ]
